name: XGBGaze
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - amply=0.1.6
  - aom=3.5.0
  - appnope=0.1.4
  - blas=2.116
  - blas-devel=3.9.0
  - bottleneck=1.3.7
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.16.0
  - certifi=2025.1.31
  - charset-normalizer=3.1.0
  - click=8.1.3
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.8
  - coin-or-utils=2.11.9
  - coincbc=2.10.10
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.0.7
  - cycler=0.11.0
  - dav1d=1.2.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - docutils=0.20.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.5.0
  - ffmpeg=6.0.0
  - filelock=3.12.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.4
  - freetype=2.12.1
  - fribidi=1.0.10
  - gensim=4.3.0
  - gettext=0.21.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graphite2=1.3.13
  - harfbuzz=7.3.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - jinja2=3.1.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=16.0.4
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvpx=1.13.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxgboost=1.7.3
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.4
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.6.0
  - nettle=3.8.1
  - networkx=3.1
  - nltk=3.8.1
  - numexpr=2.8.4
  - openblas=0.3.21
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.4.1
  - p11-kit=0.24.1
  - parso=0.8.4
  - pcre2=10.40
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.5.1
  - pooch=1.7.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pure_eval=0.2.3
  - py-xgboost=1.7.3
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2023.3
  - readline=8.2
  - regex=2023.5.5
  - scipy=1.10.1
  - setuptools=67.7.2
  - six=1.16.0
  - smart_open=6.3.0
  - stack_data=0.6.3
  - svt-av1=1.5.0
  - sympy=1.12
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.3.2
  - traitlets=5.14.3
  - unicodedata2=15.0.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.40.0
  - x264=1!164.3095
  - x265=3.5
  - xgboost=1.7.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - accelerate==0.30.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - aplr==10.8.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.8.2
      - brotli==1.1.0
      - cloudpickle==3.1.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-cytoscape==1.0.2
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - datasets==3.0.0
      - defusedxml==0.7.1
      - dill==0.3.8
      - docopt==0.6.2
      - editdistance==0.6.2
      - einops==0.7.0
      - et-xmlfile==1.1.0
      - fairscale==0.4.0
      - fastapi==0.116.1
      - fastjsonschema==2.20.0
      - ffmpy==0.4.0
      - flask==3.0.3
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gevent==24.11.1
      - gitdb==4.0.10
      - gitpython==3.1.31
      - gradio==4.44.0
      - gradio-client==1.3.0
      - gradio-image-prompter==0.1.0
      - gradio-pdf==0.0.17
      - greenlet==3.1.1
      - groovy==0.1.2
      - h11==0.14.0
      - hf-xet==1.1.9
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.34.4
      - importlib-resources==6.4.5
      - imutils==0.5.4
      - interpret==0.6.9
      - interpret-core==0.6.9
      - ipython==8.12.3
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-pygments==0.3.0
      - llvmlite==0.44.0
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markdown2==2.4.10
      - matplotlib==3.7.4
      - mdurl==0.1.2
      - mistune==3.0.2
      - modelscope-studio==0.4.0.9
      - more-itertools==10.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - narwhals==1.29.1
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - numba==0.61.0
      - numpy==1.26.4
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.5.5.64
      - openpyxl==3.1.2
      - orjson==3.10.7
      - packaging==23.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - pdf2image==1.17.0
      - peft==0.12.0
      - pillow==10.1.0
      - pipreqs==0.5.0
      - plotly==6.0.0
      - portalocker==2.10.1
      - prompt-toolkit==3.0.48
      - protobuf==4.25.0
      - psutil==5.9.5
      - pyarrow==17.0.0
      - pydantic==2.9.1
      - pydantic-core==2.23.3
      - pydub==0.25.1
      - pygments==2.18.0
      - pyreadstat==1.2.8
      - pytesseract==0.3.10
      - python-multipart==0.0.20
      - pyyaml==6.0
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - retrying==1.3.4
      - rich==13.8.1
      - rpds-py==0.20.0
      - ruff==0.12.11
      - sacrebleu==2.3.2
      - safehttpx==0.1.6
      - safetensors==0.4.5
      - salib==1.5.1
      - scikit-learn==1.6.1
      - seaborn==0.13.0
      - semantic-version==2.10.0
      - sentence-transformers==3.1.0
      - sentencepiece==0.1.99
      - sentry-sdk==1.24.0
      - shap==0.47.0
      - shellingham==1.5.4
      - shortuuid==1.0.11
      - slicer==0.0.8
      - smmap==5.0.0
      - sniffio==1.3.1
      - socksio==1.0.0
      - soupsieve==2.6
      - starlette==0.47.3
      - tabulate==0.9.0
      - timm==0.9.10
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomlkit==0.12.0
      - torch==2.1.2
      - torchvision==0.16.2
      - tqdm==4.66.5
      - transformers==4.40.0
      - typer==0.12.5
      - typing-extensions==4.15.0
      - tzdata==2025.1
      - ultralytics==8.0.109
      - uvicorn==0.24.0.post1
      - webencodings==0.5.1
      - websockets==12.0
      - werkzeug==3.0.3
      - xxhash==3.5.0
      - yarg==0.1.9
      - yarl==1.11.1
      - zope-event==5.0
      - zope-interface==7.2
